# Generated by Django 3.1.7 on 2021-03-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dregions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taddresses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tdebtdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tidcard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tpersons',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tphones',
            options={},
        ),
    ]
