# Generated by Django 3.1.7 on 2021-03-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20210316_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='taddresses',
            name='id_address_type',
            field=models.ForeignKey(blank=True, db_column='id_address_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.daddresstype'),
        ),
        migrations.AddField(
            model_name='taddresses',
            name='id_person',
            field=models.ForeignKey(blank=True, db_column='id_person', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.tpersons'),
        ),
        migrations.AddField(
            model_name='tdebtdata',
            name='id_person',
            field=models.ForeignKey(blank=True, db_column='id_person', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.tpersons'),
        ),
        migrations.AddField(
            model_name='tidcard',
            name='id_idcard_type',
            field=models.ForeignKey(blank=True, db_column='id_idcard_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.didcardtype'),
        ),
        migrations.AddField(
            model_name='tidcard',
            name='id_person',
            field=models.ForeignKey(blank=True, db_column='id_person', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.tpersons'),
        ),
        migrations.AddField(
            model_name='tpersons',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.dregions'),
        ),
        migrations.AddField(
            model_name='tphones',
            name='id_person',
            field=models.ForeignKey(blank=True, db_column='id_person', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.tpersons'),
        ),
        migrations.AddField(
            model_name='tphones',
            name='id_phone_type',
            field=models.ForeignKey(blank=True, db_column='id_phone_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.dphonetype'),
        ),
        migrations.AlterField(
            model_name='dregions',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dregions',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dregions',
            name='status',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='taddresses',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='claim_amount',
            field=models.DecimalField(decimal_places=3, max_digits=80),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='claim_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='fine_debt',
            field=models.DecimalField(decimal_places=3, max_digits=80),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='indebt_debt',
            field=models.DecimalField(decimal_places=3, max_digits=80),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='loan_amount',
            field=models.DecimalField(decimal_places=3, max_digits=80),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='main_debt',
            field=models.DecimalField(decimal_places=3, max_digits=80),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='overdue_day',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='percentage_debt',
            field=models.DecimalField(decimal_places=3, max_digits=80),
        ),
        migrations.AlterField(
            model_name='tdebtdata',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=80),
        ),
        migrations.AlterField(
            model_name='tidcard',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpersons',
            name='client_code',
            field=models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True),
        ),
        migrations.AlterField(
            model_name='tpersons',
            name='id_rollback',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='tpersons',
            name='iin',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tpersons',
            name='status',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
    ]
