# Generated by Django 3.1.7 on 2021-03-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20210316_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpersons',
            options={'managed': False},
        ),
    ]
